services:

  db_mysql:
    image: mysql:8
    container_name: mysql_hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"


  # Microservicio paciente
  paciente:
    build:
      context: ./01-paciente
      dockerfile: Dockerfile
    container_name: 01-paciente
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_paciente
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  # Microservicio medico
  medico:
    build:
      context: ./02-medico
      dockerfile: Dockerfile
    container_name: 02-medico
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_medico
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_MEDICO_URL=http://medico:8082
      - SERVICIO_ESPECIALIDADES_URL=http://especialidades:8083
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio especialidades
  especialidades:
    build:
      context: ./03-especialidades
      dockerfile: Dockerfile
    container_name: 03-especialidades
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_especialidades
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio agenda
  agenda:
    build:
      context: ./04-agenda
      dockerfile: Dockerfile
    container_name: 04-agenda
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_agendas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_MEDICO_URL=http://medico:8082
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio reservas
  reservas:
    build:
      context: ./05-reservas
      dockerfile: Dockerfile
    container_name: 05-reservas
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_reservas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
      - SERVICIO_MEDICO_URL=http://medico:8082
      - SERVICIO_AGENDA_URL=http://agenda:8084
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio consultas
  consultas:
    build:
      context: ./06-consultas
      dockerfile: Dockerfile
    container_name: 06-consultas
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_consultas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio pagos
  pagos:
    build:
      context: ./07-pagos
      dockerfile: Dockerfile
    container_name: 07-pagos
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pagos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio recetas
  recetas:
    build:
      context: ./08-recetas
      dockerfile: Dockerfile
    container_name: 08-recetas
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_recetas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
      - SERVICIO_MEDICO_URL=http://medico:8082
      - SERVICIO_RESERVAS_URL=http://reservas:8085
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio historial clinico
  historialclinico:
    build:
      context: ./09-historialclinico
      dockerfile: Dockerfile
    container_name: 09-historialclinico
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_historialclinico
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
      - SERVICIO_MEDICO_URL=http://medico:8082
      - SERVICIO_RESERVAS_URL=http://reservas:8085
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

  # Microservicio notificaciones
  notificaciones:
    build:
      context: ./10-notificaciones
      dockerfile: Dockerfile
    container_name: 10-notificaciones
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_notificaciones
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICIO_PACIENTE_URL=http://paciente:8081
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - db_mysql

volumes:
  mysql_data:

networks:
  hospital-network:
    driver: bridge